### ISSUE TITLE
error in vms_clean()

### ISSUE THREAD

**Issue by aishwarya76734** [CBMC-GCMP/dafishr#2]
https://github.com/CBMC-GCMP/dafishr/blob/c2f24edbcd32f0582035ce7fad0da02a7f2cc631/R/vms_clean.R#L68

I am trying to run preprocessing_vms only on 2016 data which has 39 files. 

the error message is: 

Error in `dplyr::mutate()`:                                                                                                            
ℹ In argument: `file_name = stringr::str_remove(path_to_data, "data/VMS-data/raw//")`.
Caused by error:
! `file_name` must be size 14625058 or 1, not 39.
Run `rlang::last_trace()` to see where the error occurred.

**Comment by Fabbiologia** [comment]
Hello Aishwarya, thank you for your interest in the package! 
I am sorry to see that you encountered a problem. 

Could you show me how you are using the `preprocessing_vms` function please?

**Comment by Fabbiologia** [comment]
Please take a look at an example usage here that worked for me: 

```
library(dafishr)

## Creating a directory where you want your file to be downloaded: 
dir.create("test/")

## Downloading data

vms_download(2016, "test/")

## getting list of the files inside the folders

vms_list <- list.files("test/", recursive=T, full.names=T, pattern = ".csv")

## Using preprocessing_vms to prepare data:

lapply(vms_list, preprocessing_vms, "test/")

```

The last one assumes you want the outputs of the preprocessing to go into the same folder "test" you created. You can customize the name of the folder as you wish.
